chrome.runtime.onMessage.addListener(
	function(request,sender, sendResponse){
		let newDiv = document.createElement("div");
		newDiv.setAttribute("id","summary");
		let header = document.createElement("h4");
		header.innerHTML="Summary generated by TLDW: ";
		newDiv.appendChild(header);
		newDiv.appendChild(document.createElement("br"));
		newDiv.appendChild(document.createTextNode(request.summary["result"]));
		let primaryInner = document.getElementById("info");
		primaryInner.appendChild(newDiv);
});
window.onhashchange= function(){    document.body.innerHTML=""; }
